# relevant snippets for setting up HA running under docker along with at least an MQTT broker in
# another docker container

# this actaully sets up to point to the docker container name of my xmqtt setup
# in fact I have used links to ensure that any host comms can be via docker container
# names where possible.  This would circumvent the need for static IP for host except for
# external items that rely upon fixed host IP. 

mqtt:
  broker: mybroker

# booleans for button actions
input_boolean:
  sprinkler_1:
  sprinkler_2:
  sprinkler_3:
  sprinkler_4: 
  sprinkler_all_stop:
  sprinkler_sound_off:


input_number:

  # this is for the integer times for sprinklers for instant on/timed off
  # ranges 5..15 minutes in 1 minute increments
  sprinkler1_time:
    name: "Sprinkler 1 time"
    icon: mdi:clock-start
    initial: 5
    min: 5
    max: 15
    step: 1
    
  # this is for the integer times for sprinklers for sun up/sun down
  # ranges 5..15 minutes in 1 minute increments
  sprinkler1_suntime:
    name: "Sprinkler 1 suntime"
    icon: mdi:clock-start
    initial: 5
    min: 5
    max: 15
    step: 1
  
